name: srsp4
description: СРСП 4 - адаптивный интерфейс Flutter (ScreenUtil, Easy Localization, Bottom Navigation Bar)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
